theme: jekyll-theme-cayman
title: Global Trend Spotter for the Advancement of the Human Condition
description: This page is devoted to introducing and explaining our groups work on using clustering techniques to understand underlying global trends in order to make recommendations on how to advance the human condition.